Subject.create(name: 'Đường lối cách mạng của Đảng Cộng sản Việt Nam', time: 'T2(1-5)-P.cs2:F305', code: '18CSH1')
Subject.create(name: 'Đường lối cách mạng của Đảng Cộng sản Việt Nam', time: 'T3(6-8)-P.cs2:F304', code: '18CTT2')
Subject.create(name: 'Cơ sở dữ liệu', time: 'T3(6-9)-P.TBSau', code: '18_1')
Subject.create(name: 'Hệ điều hành', time: 'T6(6-9)-P.TBSau', code: '18_21')
Subject.create(name: 'Cơ sở dữ liệu nâng cao', time: 'T4(1-4)-P.TBsau', code: '18_1')
Subject.create(name: 'Lập trình Windows', time: 'T2(6-9)-P.TBSau', code: '18_31')

Student.create(student_id: '18120514')
Student.create(student_id: '18120517')
Student.create(student_id: '18120519')
Student.create(student_id: '18120420')

Enrollment.create(student_id: '1', subject_id: '1')
Enrollment.create(student_id: '1', subject_id: '2')
Enrollment.create(student_id: '1', subject_id: '3')
Enrollment.create(student_id: '2', subject_id: '4')
Enrollment.create(student_id: '2', subject_id: '5')
Enrollment.create(student_id: '2', subject_id: '6')
Enrollment.create(student_id: '2', subject_id: '1')
Enrollment.create(student_id: '3', subject_id: '2')
Enrollment.create(student_id: '3', subject_id: '3')
Enrollment.create(student_id: '4', subject_id: '4')
Enrollment.create(student_id: '4', subject_id: '5')